disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - identifier_name
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - type_body_length
  - file_length
  - large_tuple